config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => '/cable'

  resources :todos do
    delete 'delete_all', on: :collection
    post 'import', on: :collection
    get 'clone', on: :member
  end

  root 'todos#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/export_csv.rb
# frozen_string_literal: true

require 'csv'
require 'active_support/concern'

module ExportCsv
  extend ActiveSupport::Concern

  HEADERS = %w[id title description done items_count created_at updated_at].freeze

  class_methods do
    def to_csv
      CSV.generate(headers: true, col_sep: ';') do |csv|
        csv << HEADERS
        includes(:items).order(:id).each do |todo|
          csv << [
            todo.id,
            todo.title,
            todo.description,
            todo.done?,
            todo.items.size,
            format_date(todo.created_at),
            format_date(todo.updated_at)
          ]
        end
      end
    end

    private

    def format_date(date)
      date&.strftime('%d/%m/%Y')
    end
  end
end

app/models/concerns/read_csv.rb
# frozen_string_literal: true

require 'csv'
require 'active_support/concern'

module ReadCsv
  extend ActiveSupport::Concern

  def read_csv(file)
    list = []

    CSV.foreach(file, headers: true, col_sep: ';') do |row|
      query = row.to_h.slice('title', 'description', 'done')
      next if Todo.exists?(query)

      list << Todo.new(row.to_h.except('id', 'items_count'))
    end

    list
  end

  def csv_valid?(file)
    return true if file_valid?(file) && format_valid?(file)

    ActionCable.server.broadcast('import_channel', message: 'Arquivo inválido, verifique formato(.csv) e os campos',
                                                   type: 'error')

    false
  end

  private

  def file_valid?(file)
    File.exist?(file) && File.extname(file) == '.csv'
  end

  def format_valid?(file)
    CSV.read(file, col_sep: ';', headers: true).headers == ExportCsv::HEADERS
  end
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :todo, inverse_of: :items

  validates :description, presence: true
end

app/models/todo.rb
# frozen_string_literal: true

class Todo < ApplicationRecord
  include ExportCsv
  extend ReadCsv

  validates :title, :description, presence: true

  has_many :items, dependent: :destroy, inverse_of: :todo

  accepts_nested_attributes_for :items, reject_if: :all_blank, allow_destroy: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/concerns/export_document.rb
# frozen_string_literal: true

require 'active_support/concern'

module ExportDocument
  extend ActiveSupport::Concern

  def template_render(format_type, locals = {}, template = 'todos/pdf.html.erb')
    render_to_string(
      **format_type,
      template: template,
      layout: 'pdf.html.erb',
      locals: locals,
      orientation: 'Landscape',
      encoding: 'UTF-8'
    )
  end

  def render_data(format, locals = {})
    send_data(template_render({ format => 'Todos' }, locals), filename: filename(format))
  end

  def filename(format_type)
    "todos_#{Time.zone.today}.#{format_type}"
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def welcome; end
end

app/controllers/todos_controller.rb
# frozen_string_literal: true

class TodosController < ApplicationController
  include ExportDocument

  before_action :set_todo, only: %i[show edit update destroy clone]

  # GET /todos or /todos.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: TodoDatatable.new(params, view_context: view_context) }
      format.csv { send_data Todo.to_csv, filename: filename('csv') }
      format.pdf { render_data(:pdf, { todos: Todo.includes(:items).all }) }
      format.docx { render_data(:docx, { todos: Todo.includes(:items).all }) }
      format.xlsx { render_data(:xlsx, { todos: Todo.includes(:items).all }) }
    end
  end

  # GET /todos/1 or /todos/1.json
  def show
    render 'todos/js/show'
  end

  # GET /todos/new
  def new
    @todo = Todo.new
    render 'todos/js/new'
  end

  # GET /todos/1/edit
  def edit
    render 'todos/js/edit'
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      format.js { render 'todos/js/create' }
      if @todo.save
        format.html { redirect_to todo_url(@todo), notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      format.js { render 'todos/js/update' }
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.js { render 'todos/js/destroy' }
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_all
    DeleteAllJob.perform_later(params[:ids])

    respond_to do |format|
      format.js { render 'todos/js/delete_all' }
      format.html { redirect_to todos_url, notice: 'Todos were successfully destroyed.' }
    end
  end

  def import
    TodoService.import(params[:file])

    render 'todos/js/import'
  end

  def clone
    @items = @todo.items.map(&:dup)
    @todo = @todo.dup
    @todo.items = @items

    render 'todos/js/clone'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_todo
    @todo = Todo.includes(:items).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def todo_params
    params
      .require(:todo)
      .permit(
        :title,
        :description,
        :done, {
          items_attributes: %I[id description status _destroy]
        }
      )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/datatable_helper.rb
# frozen_string_literal: true

module DatatableHelper
  def datatable_ajax(id:, url:, &block)
    render('shared/datatable', id: id, url: url) do
      capture(&block)
    end
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/icons_helper.rb
# frozen_string_literal: true

module IconsHelper
  def icon_regular(color = 'text-black', &block)
    "<i class='fa-regular #{block.call} #{color}'></i>".html_safe
  end

  def icon_solid(color = 'text-white', &block)
    "<i class='fa-solid #{block.call} #{color}'></i>".html_safe
  end
end

app/helpers/todos_helper.rb
# frozen_string_literal: true

module TodosHelper
end

app/views/home/welcome.html.erb
<h1 id="link-header">Home#welcome</h1>
<p>Find me in app/views/home/welcome.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxJqueryCrud</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.10.3/dist/sweetalert2.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/modal' %>
    <div class="container-scroller">
      <%= render 'shared/sidebar' %>

      <div class="container-fluid page-body-wrapper">
        <%= render 'shared/navbar' %>
        <div class="container-fluid" style="margin-top: 80px !important">
          <%= yield %>
        </div>
      </div>
    </div>

    <script src="
https://cdn.jsdelivr.net/npm/sweetalert2@11.10.3/dist/sweetalert2.all.min.js
"></script>

    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Todos - Lista</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body>
    <%= yield %>
</body>
</html>

app/views/shared/_datatable.html.erb
<table id="<%= id %>" class="table table-bordered responsive nowrap table-dark bg-dark text-dark" data-source="<%= url %>">
  <%= yield %>
</table>

app/views/shared/_modal.html.erb
<!-- Modal Bootstrap 4 -->

<div id="modal" class="modal fade" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable" role="document">
    <div id="modal-content" class="modal-content">
      <div class="modal-header bg-primary">
        <h3 id="modal-title" class="modal-title text-white"></h3>
        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close" onclick="App.Todo.closeModal();">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="content">
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar p-0 fixed-top d-flex flex-row" id="navbar">
  <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
    <a class="navbar-brand brand-logo-mini" href="/todos"></a>
  </div>
  <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
      <span class="md material-icons">menu</span>
    </button>
    <ul class="navbar-nav w-100">
      <li class="nav-item w-100">
      </li>
    </ul>
    <ul class="navbar-nav navbar-nav-right">
      <li class="nav-item dropdown">
        <a class="nav-link" id="profileDropdown" href="#" data-toggle="dropdown">
          <div class="navbar-profile">
            <p class="mb-0 mr-2 d-none d-sm-block navbar-profile-name">User</p>
            <span class="md material-icons d-none d-sm-block">menu_open</span>
          </div>
        </a>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="profileDropdown">
          <h6 class="p-3 mb-0">Profile</h6>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <span class="md material-icons text-success">settings</span>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject mb-1">Settings</p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <span class="md material-icons text-danger">logout</span>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject mb-1">Log out</p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <p class="p-3 mb-0 text-center">Advanced settings</p>
        </div>
      </li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
      <span class="md material-icons">horizontal_rule</span>
    </button>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
    <a class="sidebar-brand brand-logo" href="/todos">
    <span class="material-icons">castle</span> TODO
    <a class="sidebar-brand brand-logo-mini" href="/todos">
      <span class="material-icons">castle</span>
    </a>
  </div>
  <ul class="nav">
    <li class="nav-item nav-category">
      <span class="nav-link">Navigation</span>
    </li>
    <li class="nav-item menu-items">
      <a class="nav-link" href="/todos">
        <span class="menu-icon">
          <span class="md material-icons text-info">list</span>
        </span>
        <span class="menu-title">Todos</span>
      </a>
    </li>
    <!--
    <li class="nav-item menu-items">
      <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
        <span class="menu-icon">
          <span class="md material-icons text-warning">laptop</span>
        </span>
        <span class="menu-title">Basic UI Elements</span>
        <span class="md material-icons">keyboard_arrow_down</span>
      </a>
      <div class="collapse" id="ui-basic">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"> <a class="nav-link" href="pages/ui-features/buttons.html">Buttons</a></li>
          <li class="nav-item"> <a class="nav-link" href="pages/ui-features/dropdowns.html">Dropdowns</a></li>
          <li class="nav-item"> <a class="nav-link" href="pages/ui-features/typography.html">Typography</a></li>
        </ul>
      </div>
    </li>
    <li class="nav-item menu-items">
      <a class="nav-link" href="pages/forms/basic_elements.html">
        <span class="menu-icon">
          <span class="md material-icons text-danger">featured_play_list</span>
        </span>
        <span class="menu-title">Form Elements</span>
      </a>
    </li>
    <li class="nav-item menu-items">
      <a class="nav-link" href="pages/tables/basic-table.html">
        <span class="menu-icon">
          <span class="md material-icons text-primary">table_chart</span>
        </span>
        <span class="menu-title">Tables</span>
      </a>
    </li>
    <li class="nav-item menu-items">
      <a class="nav-link" href="pages/charts/chartjs.html">
        <span class="menu-icon">
          <span class="md material-icons text-success">leaderboard</span>
        </span>
        <span class="menu-title">Charts</span>
      </a>
    </li>
    <li class="nav-item menu-items">
      <a class="nav-link" href="pages/icons/mdi.html">
        <span class="menu-icon">
          <span class="md material-icons text-info">contacts</span>
        </span>
        <span class="menu-title">Icons</span>
      </a>
    </li>
    <li class="nav-item menu-items">
      <a class="nav-link" data-toggle="collapse" href="#auth" aria-expanded="false" aria-controls="auth">
        <span class="menu-icon">
          <span class="md material-icons text-warning">supervisor_account</span>
        </span>
        <span class="menu-title">User Pages</span>
        <span class="md material-icons">keyboard_arrow_down</span>
      </a>
      <div class="collapse" id="auth">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"> <a class="nav-link" href="pages/samples/blank-page.html"> Blank Page </a></li>
          <li class="nav-item"> <a class="nav-link" href="pages/samples/error-404.html"> 404 </a></li>
          <li class="nav-item"> <a class="nav-link" href="pages/samples/error-500.html"> 500 </a></li>
          <li class="nav-item"> <a class="nav-link" href="pages/samples/login.html"> Login </a></li>
          <li class="nav-item"> <a class="nav-link" href="pages/samples/register.html"> Register </a></li>
        </ul>
      </div>
    </li>
    <li class="nav-item menu-items">
      <a class="nav-link" href="documentation">
        <span class="menu-icon">
          <span class="md material-icons text-danger">description</span>
        </span>
        <span class="menu-title">Documentation</span>
      </a>
    </li>
    -->
  </ul>
</nav>

app/views/todos/_errors.html.erb
<div class="form-group">
  <ul class="list-group">
    <li class="list-group-item bg-danger">
      <h4 class="text-white"><%= t('errors.form', count: todo.errors.count) %></h4>
    </li>
    <% todo.errors.full_messages.each do |message| %>
      <li class="list-group-item list-group-item-danger"><%= message %></li>
    <% end %>
  </ul>
</div>

app/views/todos/_form.html.erb
<%= form_with(model: todo, remote: true, html: { id: 'todo_form' }) do |form| %>
<div class="modal-body">
  <div id="todo_errors">
  </div>

  <div class="form-group">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group form-check">
    <%= form.check_box :done, class: 'form-check-input' %>
    <%= form.label :done, class: 'form-check-label' %>
  </div>

  <div id="items">
    <div class="d-flex justify-content-between">
      <h3 id="items-count">Items: <%= form.object.items.size %></h3>
      <%= link_to_add_association form, 
                                  :items,
                                  class: 'btn btn-sm btn-primary m-3',
                                  data: {
                                    association_insertion_node: '#items',
                                    association_insertion_method: 'append',
                                    association: 'items',
                                  } do %>
        <%= icon_solid { 'fa-plus' } %> Adiciona Item
      <% end %>
    </div>

    <%= form.fields_for :items do |item| %>
      <%= render 'item_fields', f: item %>
    <% end %>
  </div>
</div>

<div class="modal-footer d-flex justify-content-between m-1">
  <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal" onclick="App.Todo.closeModal();">
    <%= icon_solid { 'fa-times' } %> Fechar
  </button>
  <button type="submit" class="btn btn-sm btn-success" data-disable-with="Salvando...">
    <%= icon_solid { 'fa-save' } %> Salvar
  </button>
</div>

<script type="text/javascript">
  App.Todo.cocoonItems();
</script>
<% end %>

app/views/todos/_item_fields.html.erb
<div class="nested-fields border p-3 mb-3">
  <div class="form-group">
    <%= f.label :description, class: 'form-label' %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="form-group form-check">
    <%= f.check_box :status, class: 'form-check-input' %>
    <%= f.label :status, "Status", class: 'form-check-label' %>
  </div>
  <%= link_to_remove_association (icon_solid {'fa-trash'} + 'Remover' ).html_safe, f, class: 'btn btn-sm btn-danger ml-1 mb-2' %>
</div>

app/views/todos/_show.html.erb
<div class="modal-body">
<p>
  <strong>Title:</strong>
  <%= todo.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= todo.description %>
</p>

<p>
  <strong>Done:</strong>
  <%= todo.done ? icon_solid { 'fa-check' } : icon_regular { 'fa-square' } %>
</p>

<h4>Items: <%= todo.items.size %></h4>

<table class="table responsive nowrap table-dark bg-dark text-white">
  <thead>
    <tr>
      <th>Descrição</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% todo.items.each do |item| %>
      <tr>
        <td><%= item.description %></td>
        <td><%= item.status ? icon_solid('text-success') { 'fa-check' } : icon_regular('text-white') { 'fa-square' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div class="modal-footer d-flex justify-content-between m-1">
  <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal" onclick="App.Todo.closeModal();">
    <%= icon_solid { 'fa-times' } %> Fechar
  </button>
</div>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <h1>Todos</h1>
</div>

<!-- Add form to import todos via file CSV -->
<div class="container-fluid">
  <%= form_tag import_todos_path, multipart: true, id: 'import_todo', remote: true do %>
    <div class="form-group">
      <%= file_field_tag :file, accept: '.csv', label: 'Arquivo CSV', class: 'form-control' %>
    </div>
    <%= submit_tag "Importar", class: 'btn btn-primary' %>
  <% end %>
</div>

<div id="new_todo" class="container-scroller mb-3"></div>

<div class="container-fluid">
  <%= datatable_ajax(id: 'todos', url: todos_path(format: :json)) do %>
    <tfoot>
      <tr>
        <th></th>
        <th>#</th>
        <th>Titulo</th>
        <th>Descrição</th>
        <th>Status</th>
        <th>Items</th>
        <th>Criado em</th>
        <th>Atualizado em</th>
        <th>Acões</th>
      </tr>
    </tfoot>
  <% end %>

  <%= link_to new_todo_path, remote: true, class: 'btn btn-primary', id: 'new_todo' do %>
    <%= icon_solid {'fa-plus'} %> Criar TODO
  <% end %>
</div>

<script type="text/javascript">
  $(document).on('turbolinks:load', function() {
    // Load table
    App.Todo.load_table();
  });

  // Submit form to import todos
  $('#import_todo').on('submit', function(e) {
    e.preventDefault();

    var form = $(this);

    if(form.find('input[type="file"]').val() == '') {
      Toast.error('Selecione um arquivo para importar');
      form[0].reset();
      $('input[type="submit"]').prop('disabled', false);
      return false;
    }else{
      App.Todo.import(form, this);
    }
  });
</script>

app/views/todos/js/clone.js.erb
$('turbolinks:load').ready( function() {
  App.Modal.show('Novo Todo - Clone', "<%=j render 'form', todo: @todo %>");
});

app/views/todos/js/create.js.erb
$('turbolinks:load').ready(function() {
  <!-- Verifica se não houve nenhum erro e carrega os dados através da chamada AJAX -->
  <% if @todo.errors.empty? %>
    <!-- Fecha o modal -->
    App.Modal.close();

    <!-- Recarrega o datatable usando a chamada AJAX -->
    App.Todo.refreshDataTableAjax();

    Toast.success('Todo Criado com sucesso !')

  <!-- Se houver erro recarrega o modal -->
  <% else %>
    <!-- Renderiza os erros -->
    App.Modal.setErrors('<%= j render 'errors', todo: @todo %>');

    <!-- Exibe mensagem de erro -->
    Toast.error('Erro ao criar Todo !')
  <% end %>
});

app/views/todos/js/delete_all.js.erb
$('turbolinks:load').ready(function() {
  <!-- Exibe mensagem de sucesso -->
  Toast.success("Exclusão em lote inicializada!")
});

app/views/todos/js/destroy.js.erb
$('turbolinks:load').ready(function() {
  <!-- Atualiza a tabela -->
  App.Todo.refreshDataTableAjax();

  <!-- Exibe mensagem de sucesso -->
  Toast.success('Removido com sucesso!');
});

app/views/todos/js/edit.js.erb
$('turbolinks:load').ready( function() {
  App.Modal.show('Editar Todo', "<%=j render 'form', todo: @todo %>");
});

app/views/todos/js/import.js.erb
$('turbolinks:load').ready( function() {
Toast.success('Importação iniciada aguarde alguns instantes!');
});

app/views/todos/js/new.js.erb
$('turbolinks:load').ready( function() {
  App.Modal.show('Novo Todo', "<%=j render 'form', todo: @todo %>");
});

app/views/todos/js/show.js.erb
$('turbolinks:load').ready( function() {
  App.Modal.show('Todo', "<%=j render 'show', todo: @todo %>");
});

app/views/todos/js/update.js.erb
$('turbolinks:load').ready(function() {

  <!-- Verifica se não teve algum erro -->
  <% if @todo.errors.empty? %>

    <!-- Fecha modal -->
    App.Modal.close();

    <!-- Recarrega o datatable -->
    App.Todo.refreshDataTableAjax();

    <!-- Exibe mensagem de sucesso -->
    Toast.success('Atualizado com sucesso!');

  <!-- Senão recarrega o modal com os erros -->
  <% else %>
    <!-- Renderiza os erros -->
    App.Modal.setErrors('<%= j render 'errors', todo: @todo %>');

    <!-- Exibe mensagem de erro -->
    Toast.error('Preencha todos os campos!');
  <% end %>
});

app/views/todos/pdf.html.erb
<h1>Lista de Todos</h1>
  <table id="todos" class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>#</th>
        <th>Titulo</th>
        <th>Descrição</th>
        <th>Status</th>
        <th>Total de Items</th>
        <th>Criado em</th>
        <th>Atualizado em</th>
      </tr>
    </thead>
    <tbody>
      <% todos.each do |todo| %>
        <tr>
          <td><%= todo.id %></td>
          <td><%= todo.title %></td>
          <td><%= todo.description %></td>
          <td><%= todo.done ? 'Feito' : 'Esperando' %></td>
          <td><%= todo.items.size %></td>
          <td><%= todo.created_at.strftime("%d/%m/%Y") %></td>
          <td><%= todo.updated_at.strftime("%d/%m/%Y") %></td>
        </tr>
      <% end %>
    </tbody>
    <tfooter>
      <tr>
        <th>#</th>
        <th>Titulo</th>
        <th>Descrição</th>
        <th>Status</th>
        <th>Total de Items</th>
        <th>Criado em</th>
        <th>Atualizado em</th>
      </tr>
      <tr>
        <td colspan="2">Total de Registros</td>
        <td colspan="5"><%= todos.size %></td>
      </tr>
    </tfooter>
  </table>